export var nombre;
export var apellido;
export var edad;
export var fechaDeNacimiento;
export var direccion;
nombre = "Nestor";
apellido = "Fernandez";
edad = 29;
fechaDeNacimiento = "14-may-1995";
direccion = "Buena Fe";